### PR TITLE
handle relative paths for self-hosted gitlab

### LINKED ISSUE #7: Gbrowse doesn't work with locally hosted gitlab under a relative path
Our gitlab is hosted at `https://example.com/gitlab` but the remote is `git@example.com`. `:Gbrowse` results in `fugitive: "origin' is not a supported remote`

### PR DESCRIPTION
**Pull request by chelming**
adds the relative path back in for ssh-style remotes. Https style remotes already have the relative path built in so it leaves those alone.

`git@example.com/user/repo.git` will update to `https://example.com/rel_path/user/repo`
`https://example.com/rel_path/user/repo.git` will not be updated to add the relative path since it's already there and will pass the path correctly.

Fixes #7

### CODE REVIEW

**Comment by cwhits** [comment]
I _don't_ know what will happen if there are multiple gitlab domains entered for `g:fugitive_gitlab_domains`. My commit would probably break that if one had a relative URL and one didn't. Maybe it needs a dictionary to relate the relative path to the repo?

**Comment by chelming** [comment]
I _don't_ know what will happen if there are multiple gitlab domains entered for g:fugitive_gitlab_domains. My commit would probably break that if one had a relative URL and one didn't. Maybe it needs a dictionary to relate the relative path to the repo?

**Comment by shumphrey** [comment]
From first glance looks good. Away from computer for a couple of days but will look further asap.

**Comment by chelming** [comment]
I switched it to using a dictionary so it will look up whether there's a relative path for a specific repo.

`let rel_path[domain_root] = domain_path`

Let me know what you think...

**Comment by shumphrey** [comment]
Had to make a small adjustment as the domain didn't exist for http URLs, causing a dictionary lookup failure.

**Comment by shumphrey** [comment]
Thanks!

**Pull request merged**
